import { createClient } from '@supabase/supabase-js';
import dotenv from 'dotenv';
import path from 'path';

dotenv.config({ path: path.resolve(process.cwd(), '.env.local') });

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseAnonKey) {
  console.error("Missing Supabase credentials in .env.local");
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseAnonKey);

const culturalAssets = [
  {
    id: 'wayang-kulit-jawa',
    title: 'Wayang Kulit',
    subtitle: 'Singularitas Bayangan',
    category: 'kriya',
    description: 'Seni pertunjukan bayangan yang berusia lebih dari seribu tahun. Dalang menghidupkan tokoh-tokoh epik Mahabharata dan Ramayana melalui kulit kerbau yang diukir dengan presisi tak tertandingi.',
    region: 'Jawa Tengah',
    province: 'Jawa Tengah',
    lat: -7.150975, lng: 110.140259,
    status_extinction: 'rentan',
    cover_image: '/images/wayang.jpg',
    tags: ['UNESCO', 'Pertunjukan', 'Filosofi', 'Kulit'],
    media_count_image: 48, media_count_audio: 12, media_count_video: 6,
    contributors: 234, views: 18420, created_at: '2024-01-15T00:00:00Z', featured: true,
  },
  {
    id: 'batik-pedalaman',
    title: 'Batik Pedalaman',
    subtitle: 'Kode Visual Nusantara',
    category: 'kriya',
    description: 'Batik bukan sekadar kain — ia adalah manuskrip visual yang menyimpan kosmologi Jawa. Setiap motif — Parang, Kawung, Sido Mukti — membawa pesan tentang alam semesta, kekuasaan, dan doa.',
    region: 'Solo, Yogyakarta',
    province: 'Jawa Tengah',
    lat: -7.5755, lng: 110.8243,
    status_extinction: 'rentan',
    cover_image: '/images/batik.jpg',
    tags: ['UNESCO', 'Tenun', 'Malam', 'Motif'],
    media_count_image: 92, media_count_audio: 4, media_count_video: 8,
    contributors: 412, views: 32100, created_at: '2024-02-20T00:00:00Z', featured: true,
  },
  {
    id: 'gamelan-jawa',
    title: 'Gamelan Jawa',
    subtitle: 'Frekuensi Kosmik Nusantara',
    category: 'musik',
    description: 'Orkestra perkusi terdiri dari instrumen perunggu, kayu, dan kulit. Sistem tangga nada Slendro dan Pelog adalah teknologi akustik tertua di dunia yang menghubungkan manusia dengan alam semesta.',
    region: 'Yogyakarta & Solo',
    province: 'Jawa Tengah',
    lat: -7.7956, lng: 110.3695,
    status_extinction: 'rentan',
    cover_image: '/images/gamelan.jpg',
    tags: ['UNESCO', 'Perunggu', 'Slendro', 'Pelog'],
    media_count_image: 32, media_count_audio: 24, media_count_video: 5,
    contributors: 189, views: 24500, created_at: '2024-03-10T00:00:00Z', featured: true,
  },
  {
    id: 'tari-saman',
    title: 'Tari Saman',
    subtitle: 'Sinkronisasi Ribuan Tangan',
    category: 'tari',
    description: 'Tarian seribu tangan dari dataran tinggi Gayo. Para penari menggunakan tepukan dada, paha, dan tangan untuk menciptakan ritme yang menggelegar dan presisi matematis tanpa iringan alat musik.',
    region: 'Gayo, Aceh',
    province: 'Aceh',
    lat: -4.011, lng: 97.43,
    status_extinction: 'aman',
    cover_image: '/images/saman.jpg',
    tags: ['UNESCO', 'Gayo', 'Tepukan', 'Harmoni'],
    media_count_image: 56, media_count_audio: 8, media_count_video: 12,
    contributors: 156, views: 21000, created_at: '2023-11-05T00:00:00Z', featured: false,
  },
  {
    id: 'bahasa-enggano',
    title: 'Bahasa Enggano',
    subtitle: 'Sandi Vokal Samudra',
    category: 'bahasa',
    description: 'Bahasa Austronesia yang sangat terisolasi, dituturkan oleh penduduk Pulau Enggano. Dengan kurang dari 1.000 penutur aktif, bahasa ini menyimpan sistem klasifikasi alam dan laut yang unik.',
    region: 'Pulau Enggano',
    province: 'Bengkulu',
    lat: -5.3944, lng: 102.2711,
    status_extinction: 'kritis',
    cover_image: '/images/enggano.jpg',
    tags: ['Bahasa', 'Austronesia', 'Isolat', 'Lisan'],
    media_count_image: 5, media_count_audio: 42, media_count_video: 2,
    contributors: 12, views: 4320, created_at: '2024-04-01T00:00:00Z', featured: false,
  },
  {
    id: 'ritual-pasola',
    title: 'Pasola',
    subtitle: 'Darah dan Kesuburan Bumi',
    category: 'ritual',
    description: 'Ritual perang berkuda masyarakat Sumba untuk merayakan musim tanam. Darah yang tumpah dari lemparan lembing kayu diyakini akan menyuburkan tanah — sinkretisme antara keberanian dan penghormatan pada alam.',
    region: 'Sumba Barat',
    province: 'Nusa Tenggara Timur',
    lat: -9.6417, lng: 119.4144,
    status_extinction: 'aman',
    cover_image: '/images/pasola.jpg',
    tags: ['Marapu', 'Kuda', 'Lembing', 'Agrikultur'],
    media_count_image: 120, media_count_audio: 15, media_count_video: 25,
    contributors: 89, views: 15600, created_at: '2023-08-12T00:00:00Z', featured: false,
  },
  {
    id: 'angklung-sunda',
    title: 'Angklung',
    subtitle: 'Harmoni Bambu Parahyangan',
    category: 'musik',
    description: 'Alat musik tradisional dari Jawa Barat terbuat dari tabung bambu. Setiap angklung menghasilkan satu nada saja, sehingga membutuhkan kerja sama kolektif untuk menciptakan melodi yang utuh.',
    region: 'Sunda',
    province: 'Jawa Barat',
    lat: -6.9147, lng: 107.6098,
    status_extinction: 'aman',
    cover_image: '/images/angklung.jpg',
    tags: ['UNESCO', 'Bambu', 'Sunda', 'Gotong Royong'],
    media_count_image: 65, media_count_audio: 18, media_count_video: 14,
    contributors: 210, views: 28400, created_at: '2024-04-10T00:00:00Z', featured: true,
  },
  {
    id: 'tari-kecak',
    title: 'Tari Kecak',
    subtitle: 'Paduan Suara Magis Dewata',
    category: 'tari',
    description: 'Pertunjukan khas Bali di mana ratusan pria duduk melingkar menyerukan "cak" secara ritmis. Tarian ini menceritakan epos Ramayana dan berakar dari ritual sanghyang penolakan bala.',
    region: 'Uluwatu, Gianyar',
    province: 'Bali',
    lat: -8.8291, lng: 115.0886,
    status_extinction: 'aman',
    cover_image: '/images/kecak.jpg',
    tags: ['Bali', 'Ramayana', 'Acapella', 'Sakral'],
    media_count_image: 104, media_count_audio: 22, media_count_video: 30,
    contributors: 340, views: 45000, created_at: '2023-12-05T00:00:00Z', featured: true,
  },
  {
    id: 'keris-indonesia',
    title: 'Keris',
    subtitle: 'Bilah Bertuah Nusantara',
    category: 'kriya',
    description: 'Senjata tikam asimetris dengan pamor khas. Lebih dari sekadar senjata, keris adalah objek spiritual, simbol status sosial, dan mahakarya metalurgi yang memadukan besi, baja, dan meteorit (pamor).',
    region: 'Jawa, Bali, Sumatera',
    province: 'Jawa Tengah',
    lat: -7.8014, lng: 110.3644,
    status_extinction: 'rentan',
    cover_image: '/images/keris.jpg',
    tags: ['UNESCO', 'Pusaka', 'Metalurgi', 'Spiritual'],
    media_count_image: 88, media_count_audio: 5, media_count_video: 10,
    contributors: 145, views: 19800, created_at: '2024-01-22T00:00:00Z', featured: false,
  },
  {
    id: 'noken-papua',
    title: 'Noken',
    subtitle: 'Rajutan Kehidupan Hutan',
    category: 'kriya',
    description: 'Tas rajut tradisional khas Papua yang dibawa dengan dahi atau kepala. Noken melambangkan kedewasaan perempuan Papua dan digunakan untuk membawa hasil pertanian, kayu bakar, hingga menggendong anak.',
    region: 'Pegunungan Tengah Papua',
    province: 'Papua',
    lat: -4.2699, lng: 138.0804,
    status_extinction: 'rentan',
    cover_image: '/images/noken.jpg',
    tags: ['UNESCO', 'Rajutan', 'Papua', 'Simbol Kehidupan'],
    media_count_image: 42, media_count_audio: 2, media_count_video: 8,
    contributors: 67, views: 11200, created_at: '2023-09-15T00:00:00Z', featured: false,
  },
  {
    id: 'rendang-minang',
    title: 'Rendang',
    subtitle: 'Seni Karamelisasi Rempah',
    category: 'kuliner',
    description: 'Masakan daging berbumbu rempah yang diproses dengan pemanasan berulang bersama santan kelapa. Teknik memasak lambat ini tidak hanya mengawetkan daging, tetapi juga melambangkan kesabaran dan kebijaksanaan Minangkabau.',
    region: 'Minangkabau',
    province: 'Sumatera Barat',
    lat: -0.9471, lng: 100.4172,
    status_extinction: 'aman',
    cover_image: '/images/rendang.jpg',
    tags: ['Kuliner', 'Minangkabau', 'Rempah', 'Slow Cooking'],
    media_count_image: 115, media_count_audio: 3, media_count_video: 15,
    contributors: 420, views: 55000, created_at: '2023-07-20T00:00:00Z', featured: true,
  },
  {
    id: 'pencak-silat',
    title: 'Pencak Silat',
    subtitle: 'Gerak Refleks Estetik',
    category: 'permainan',
    description: 'Seni bela diri tradisional yang mengakar dalam budaya Melayu dan Nusantara. Menggabungkan aspek mental-spiritual, bela diri, seni, dan olahraga. Setiap aliran terinspirasi dari gerak alam dan hewan.',
    region: 'Nusantara',
    province: 'DKI Jakarta',
    lat: -6.2088, lng: 106.8456,
    status_extinction: 'aman',
    cover_image: '/images/silat.jpg',
    tags: ['UNESCO', 'Bela Diri', 'Olahraga', 'Spiritual'],
    media_count_image: 75, media_count_audio: 10, media_count_video: 45,
    contributors: 310, views: 38900, created_at: '2023-10-18T00:00:00Z', featured: false,
  },
  {
    id: 'sasando-rote',
    title: 'Sasando',
    subtitle: 'Denting Dawai Lontar',
    category: 'musik',
    description: 'Alat musik petik tradisional dari Pulau Rote dengan resonator dari daun lontar yang dirangkai melingkar. Suara sasando sangat khas, mirip perpaduan antara harpa, gitar, dan kecapi.',
    region: 'Pulau Rote',
    province: 'Nusa Tenggara Timur',
    lat: -10.7325, lng: 123.1189,
    status_extinction: 'rentan',
    cover_image: '/images/sasando.jpg',
    tags: ['Rote', 'Petik', 'Lontar', 'Dawai'],
    media_count_image: 28, media_count_audio: 35, media_count_video: 12,
    contributors: 55, views: 14500, created_at: '2024-02-14T00:00:00Z', featured: false,
  },
  {
    id: 'reog-ponorogo',
    title: 'Reog Ponorogo',
    subtitle: 'Tarian Magis Singa Barong',
    category: 'tari',
    description: 'Seni pertunjukan yang menampilkan topeng kepala singa raksasa berhiaskan bulu merak (Singo Barong) berbobot hingga 50 kg, ditarikan hanya dengan kekuatan gigi penari. Sarat nilai heroisme dan mistis.',
    region: 'Ponorogo',
    province: 'Jawa Timur',
    lat: -7.8681, lng: 111.4651,
    status_extinction: 'rentan',
    cover_image: '/images/reog.jpg',
    tags: ['Ponorogo', 'Topeng', 'Mistis', 'Barong'],
    media_count_image: 60, media_count_audio: 15, media_count_video: 22,
    contributors: 132, views: 26700, created_at: '2024-05-01T00:00:00Z', featured: true,
  },
  {
    id: 'kapal-pinisi',
    title: 'Kapal Pinisi',
    subtitle: 'Mahakarya Maritim Bugis',
    category: 'kriya',
    description: 'Seni pembuatan perahu layar tradisional Suku Bugis-Makassar. Dibuat tanpa paku besi dan cetak biru tertulis, pinisi adalah bukti kejayaan teknologi maritim Nusantara yang mampu mengarungi samudra dunia.',
    region: 'Bulukumba',
    province: 'Sulawesi Selatan',
    lat: -5.3344, lng: 120.3161,
    status_extinction: 'rentan',
    cover_image: '/images/pinisi.jpg',
    tags: ['UNESCO', 'Maritim', 'Bugis', 'Perahu'],
    media_count_image: 85, media_count_audio: 4, media_count_video: 18,
    contributors: 110, views: 22400, created_at: '2023-11-20T00:00:00Z', featured: false,
  },
  {
    id: 'tenun-ikat-ntt',
    title: 'Tenun Ikat NTT',
    subtitle: 'Benang Pencerita Leluhur',
    category: 'kriya',
    description: 'Kain tenun ikat dari Nusa Tenggara Timur yang dibuat dengan teknik mengikat benang sebelum dicelup pewarna alami. Setiap motif menceritakan mitologi, status sosial, dan penghormatan kepada leluhur pembuatnya.',
    region: 'Flores, Sumba, Timor',
    province: 'Nusa Tenggara Timur',
    lat: -8.6574, lng: 122.1674,
    status_extinction: 'rentan',
    cover_image: '/images/tenun-ntt.jpg',
    tags: ['Tenun', 'Motif', 'Pewarna Alam', 'Leluhur'],
    media_count_image: 72, media_count_audio: 6, media_count_video: 9,
    contributors: 98, views: 16800, created_at: '2023-10-01T00:00:00Z', featured: false,
  },
  {
    id: 'tari-pendet',
    title: 'Tari Pendet',
    subtitle: 'Persembahan Agung Dewata',
    category: 'tari',
    description: 'Tarian ritual penyambutan dari Bali yang awalnya hanya dipentaskan di pura sebagai persembahan kepada dewa. Kini berkembang menjadi tarian ucapan selamat datang, namun tetap menyimpan nilai sakralitas yang tinggi.',
    region: 'Bali',
    province: 'Bali',
    lat: -8.3405, lng: 115.0920,
    status_extinction: 'aman',
    cover_image: '/images/pendet.jpg',
    tags: ['Bali', 'Sakral', 'Pura', 'Persembahan'],
    media_count_image: 90, media_count_audio: 12, media_count_video: 20,
    contributors: 180, views: 33500, created_at: '2024-03-22T00:00:00Z', featured: false,
  },
  {
    id: 'rumah-adat-toraja',
    title: 'Rumah Tongkonan',
    subtitle: 'Kapal di Atas Darat',
    category: 'kriya',
    description: 'Rumah adat masyarakat Toraja dengan atap melengkung seperti perahu terbalik, dihiasi ukiran warna merah, hitam, dan kuning bermakna simbolis. Tongkonan bukan sekadar tempat tinggal, melainkan pusat silsilah dan identitas klan.',
    region: 'Toraja',
    province: 'Sulawesi Selatan',
    lat: -2.9490, lng: 119.8682,
    status_extinction: 'rentan',
    cover_image: '/images/tongkonan.jpg',
    tags: ['Arsitektur', 'Toraja', 'Ukiran', 'Leluhur'],
    media_count_image: 95, media_count_audio: 7, media_count_video: 13,
    contributors: 125, views: 20100, created_at: '2024-01-08T00:00:00Z', featured: false,
  },
  {
    id: 'bahasa-tobati',
    title: 'Bahasa Tobati',
    subtitle: 'Suara Terakhir Teluk Yos Sudarso',
    category: 'bahasa',
    description: 'Bahasa papuan yang hanya dituturkan oleh belasan orang di Teluk Yos Sudarso, Jayapura. Merupakan salah satu bahasa paling terancam punah di Indonesia, menyimpan kosakata ekologi dan kemaritiman yang tak tertandingi.',
    region: 'Jayapura',
    province: 'Papua',
    lat: -2.5337, lng: 140.7181,
    status_extinction: 'kritis',
    cover_image: '/images/tobati.jpg',
    tags: ['Bahasa', 'Papua', 'Terancam', 'Papuan'],
    media_count_image: 8, media_count_audio: 55, media_count_video: 3,
    contributors: 9, views: 3200, created_at: '2024-04-18T00:00:00Z', featured: false,
  },
  {
    id: 'upacara-ngaben',
    title: 'Ngaben',
    subtitle: 'Api Penyucian Sang Atma',
    category: 'ritual',
    description: 'Upacara kremasi sakral umat Hindu Bali untuk membebaskan roh dari ikatan duniawi agar dapat bereinkarnasi atau mencapai moksha. Prosesi ini melibatkan pembuatan lembu atau sarkofagus berbentuk hewan yang dibakar bersama jenazah.',
    region: 'Seluruh Bali',
    province: 'Bali',
    lat: -8.4095, lng: 115.1889,
    status_extinction: 'aman',
    cover_image: '/images/ngaben.jpg',
    tags: ['Hindu', 'Bali', 'Kremasi', 'Moksha'],
    media_count_image: 130, media_count_audio: 18, media_count_video: 35,
    contributors: 260, views: 41000, created_at: '2023-06-15T00:00:00Z', featured: true,
  },
  {
    id: 'ukiran-asmat',
    title: 'Ukiran Asmat',
    subtitle: 'Dialog dengan Roh Leluhur',
    category: 'kriya',
    description: 'Seni ukir kayu Suku Asmat Papua yang menggambarkan arwah leluhur (mbis). Setiap patung atau perisai ukir memiliki makna ritual yang mendalam. Ukiran Asmat diakui sebagai salah satu seni tribal terbaik di dunia.',
    region: 'Agats, Asmat',
    province: 'Papua Selatan',
    lat: -5.5444, lng: 138.1186,
    status_extinction: 'rentan',
    cover_image: '/images/asmat.jpg',
    tags: ['Asmat', 'Ukiran', 'Tribal', 'Papua'],
    media_count_image: 68, media_count_audio: 8, media_count_video: 11,
    contributors: 78, views: 17500, created_at: '2024-02-08T00:00:00Z', featured: false,
  },
  {
    id: 'tari-tor-tor',
    title: 'Tor-Tor',
    subtitle: 'Getaran Tanah Batak',
    category: 'tari',
    description: 'Tarian sakral masyarakat Batak Toba yang dipentaskan dalam upacara adat, peringatan leluhur, dan perayaan penting. Gerakan berirama lambat dan penuh wibawa, diiringi gondang sabangunan yang menggetarkan bumi.',
    region: 'Samosir, Toba',
    province: 'Sumatera Utara',
    lat: 2.6035, lng: 98.8762,
    status_extinction: 'rentan',
    cover_image: '/images/tortor.jpg',
    tags: ['Batak', 'Sakral', 'Gondang', 'Toba'],
    media_count_image: 55, media_count_audio: 20, media_count_video: 15,
    contributors: 103, views: 18900, created_at: '2023-09-01T00:00:00Z', featured: false,
  },
  {
    id: 'jamu-tradisional',
    title: 'Jamu Tradisional',
    subtitle: 'Farmakologi Rempah Nusantara',
    category: 'kuliner',
    description: 'Sistem pengobatan tradisional berbasis tanaman rempah dan herbal yang telah dipraktikkan selama ratusan tahun di Jawa. Setiap racikan jamu memiliki khasiat spesifik berdasarkan filosofi keseimbangan unsur alam dalam tubuh manusia.',
    region: 'Jawa',
    province: 'Jawa Tengah',
    lat: -7.6298, lng: 110.8307,
    status_extinction: 'rentan',
    cover_image: '/images/jamu.jpg',
    tags: ['UNESCO', 'Herbal', 'Pengobatan', 'Rempah'],
    media_count_image: 78, media_count_audio: 5, media_count_video: 10,
    contributors: 195, views: 29600, created_at: '2024-03-30T00:00:00Z', featured: false,
  },
  {
    id: 'tari-piring',
    title: 'Tari Piring',
    subtitle: 'Api di Telapak Tangan',
    category: 'tari',
    description: 'Tarian tradisional Minangkabau di mana penari membawa piring di telapak tangan dan menari di atas pecahan kaca tanpa terluka. Berasal dari ritual syukur panen kepada dewa-dewa sebelum masuknya Islam ke Minangkabau.',
    region: 'Solok, Padang',
    province: 'Sumatera Barat',
    lat: -0.7893, lng: 100.6503,
    status_extinction: 'aman',
    cover_image: '/images/tari-piring.jpg',
    tags: ['Minangkabau', 'Piring', 'Ritual', 'Akrobatik'],
    media_count_image: 64, media_count_audio: 14, media_count_video: 16,
    contributors: 144, views: 23700, created_at: '2024-01-30T00:00:00Z', featured: false,
  },
  {
    id: 'ondel-ondel',
    title: 'Ondel-Ondel',
    subtitle: 'Raksasa Penjaga Betawi',
    category: 'ritual',
    description: 'Boneka raksasa khas Betawi setinggi dua meter yang awalnya berfungsi sebagai penolak bala dan roh jahat. Kini menjadi ikon budaya Betawi yang kerap tampil dalam festival, pernikahan, dan perayaan kemerdekaan.',
    region: 'Jakarta',
    province: 'DKI Jakarta',
    lat: -6.2146, lng: 106.8451,
    status_extinction: 'rentan',
    cover_image: '/images/ondel-ondel.jpg',
    tags: ['Betawi', 'Boneka', 'Penolak Bala', 'Jakarta'],
    media_count_image: 50, media_count_audio: 10, media_count_video: 20,
    contributors: 115, views: 25300, created_at: '2023-12-20T00:00:00Z', featured: false,
  },
];

async function seed() {
  console.log('Seeding Supabase Database dengan ' + culturalAssets.length + ' warisan budaya...');

  const { error: deleteError } = await supabase.from('cultural_assets').delete().neq('id', 'dummy');
  if (deleteError) {
    console.error('Error clearing old data:', deleteError.message);
  }

  const { error } = await supabase.from('cultural_assets').insert(culturalAssets);

  if (error) {
    console.error('Seeding failed:', error.message);
  } else {
    console.log('Seeding berhasil! ' + culturalAssets.length + ' warisan budaya berhasil diunggah ke Supabase.');
  }
}

seed();
